/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ActivityLogResponseData {
  message_id?: number;
  meeting_id?: number;
  content?: string;
  /**
   * 0 -> User message, 1 -> create, 2 -> edit, 3 -> join, 4 -> delete, 5 -> cancel, 6 -> addParticipants, 7 -> updateParticipantStatus, 8 -> removeParticipants, 9 -> update phone number, 10 -> delete account
   */
  system_generated?: number;
  created_at?: string;
  contact_number?: string;
  registration_status?: boolean;
  is_deleted?: boolean;
}
