/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActivityLogResponseData } from './activityLogResponseData';

export interface ActivityLogResponse {
  is_error?: boolean;
  status_code?: number;
  display_msg?: string;
  latest_previous_index?: number;
  res_data?: Array<ActivityLogResponseData>;
}
