/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This deletes the messages from the users screen
 */
export interface ChatDeleteUserMessage {
  /**
   * list of message_ids which are to be deleted in the system
   */
  message_ids?: Array<number>;
}
