/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * To get a message history, client emits this events. Socket send the response through message-history
 */
export interface ChatGetMessageHistory {
  /**
   * meeting_id
   */
  meeting_id?: number;
}
