/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This gives the message list which were delivered to all the participants in the group
 */
export interface ChatDeliveredToAll {
  /**
   * list of message_ids which are delivered to all
   */
  message_ids?: Array<number>;
}
