/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateRegistrationResponse {
  /**
   * The app_key of the user. Keep it confidential.
   */
  app_key?: string;
  /**
   * true -> if user is already registered. Otherwise false.
   */
  user_exist?: boolean;
  /**
   * The login_method type that the user is already registered. 0 - default.
   */
  login_method?: number;
  /**
   * The recovery login_id the user if he is already registered.
   */
  login_id?: string;
  /**
   * The recovery email_id the user if he is already registered.
   */
  email_id?: string;
  /**
   * custom field.
   */
  request_otp?: boolean;
}
