/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DeleteMeeting {
  /**
   * 1 - To delete the whole series,0 - To delete a specific meeting
   */
  set_recurrence: number;
  /**
   * The recur_meeting_id of the meeting to be deleted.
   */
  recur_meeting_id: number;
  /**
   * The meeting_id of the meeting to be deleted.
   */
  meeting_id: number;
}
