/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EditMeeting {
  /**
   * 1 - To update the whole series,0 - To update the specific meeting
   */
  set_recurrence: number;
  /**
   * The recur_meeting_id of the meeting.
   */
  recur_meeting_id: number;
  /**
   * The meeting_id of the meeting.
   */
  meeting_id: number;
  /**
   * The updated subject of the meeting.
   */
  subject?: string;
  /**
   * The updated start date and time of the meeting in YYYY-MM-DD HH:mm:SS format.
   */
  start_time?: string;
  /**
   * The updated end date and time of the meeting in YYYY-MM-DD HH:mm:SS format.
   */
  end_time?: string;
  /**
   * The updated location of the meeting.
   */
  location?: string;
  /**
   * The updated latitude of the location of the meeting.
   */
  latitude?: string;
  /**
   * The updated longitude of the location of the meeting.
   */
  longitude?: string;
}
