/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GetParticipants {
  /**
   * The meeting_id of the meeting from which the participants to be fetched.
   */
  meeting_id: number;
  /**
   * The request type defines which participants should be fetched
   */
  request_type: number;
  /**
   * This field defines the next participant to be fetched
   */
  previous_index: number;
  /**
   * Maximum number of participants to be fetched.
   */
  max_limit: number;
}
