/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GroupParticipants {
  /**
   * The registration status of the user with catchup
   */
  registration_status?: boolean;
  /**
   * Contact number of the participant
   */
  contact_number?: string;
  /**
   * participant added date and time
   */
  added_at?: string;
}
