/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupParticipants } from './groupParticipants';

export interface GroupInfoResponseData {
  /**
   * group_id of the group
   */
  group_id?: number;
  /**
   * title of the group
   */
  title?: string;
  created_at?: string;
  /**
   * list of participants objects
   */
  participants?: Array<GroupParticipants>;
}
