/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse20011ResData {
  /**
   * meeting_id of the meeting
   */
  meeting_id?: number;
  /**
   * recur_meeting_id of the meeting
   */
  recur_meeting_id?: number;
}
