/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface JoinMeeting {
  /**
   * Either registration_link or recur_meeting_id must be passed.
   */
  recur_meeting_id?: number;
  /**
   * Either registration_link or recur_meeting_id must be passed.
   */
  registration_link?: string;
  /**
   * Whether to join the series or specific meeting
   */
  set_recurrence?: number;
  /**
   * The status of the participant (accepted/declined/tentatively accepted)
   */
  status?: number;
}
