/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LocationInfoResponseData {
  /**
   * index of the location.
   */
  id?: number;
  /**
   * Code of the location.
   */
  code?: string;
  /**
   * Name of the location.
   */
  name?: string;
  /**
   * Latitude of the location to be created.
   */
  latitude?: string;
  /**
   * Longitude of the location to be created.
   */
  longitude?: string;
}
