/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MeetingParticipants } from './meetingParticipants';

export interface MeetingInfoResponseData {
  /**
   * recur_meeting_id of the meeting
   */
  recur_meeting_id?: number;
  /**
   * meeting_id of the meeting
   */
  meeting_id?: number;
  /**
   * chat room_id of the meeting
   */
  room_id?: string;
  /**
   * subject of the meeting
   */
  subject?: string;
  /**
   * start time of the meeting
   */
  start_time?: string;
  /**
   * end time of the meeting
   */
  end_time?: string;
  /**
   * Location of the meeting
   */
  location?: string;
  /**
   * Longitude of the meeting
   */
  longitude?: string;
  /**
   * Latitude of the meeting
   */
  latitude?: string;
  /**
   * If new participants can be added by existing  participants or not.
   */
  allow_forwarding?: boolean;
  /**
   * if the meeting is already cancelled or not.
   */
  is_cancelled?: boolean;
  /**
   * if the meeting is already deactivated or not.
   */
  is_deactivated?: boolean;
  /**
   * latest updated time of the meeting
   */
  updated_at?: string;
  created_at?: string;
  set_recurrence?: number;
  repeat_interval?: number;
  repeat_mode?: number;
  repeat_count?: number;
  event_category?: number;
  registration_link?: string;
  firebase_link?: string;
  link_active?: boolean;
  max_participant_limit?: number;
  /**
   * list of participants objects
   */
  participants?: Array<MeetingParticipants>;
}
