/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MeetingParticipants {
  /**
   * Contact number of the participant
   */
  contact_number?: string;
  /**
   * The registration status of the user with catchup
   */
  registration_status?: boolean;
  /**
   * The participant status of the meeting(accepted/denied)
   */
  status?: number;
  /**
   * if the participant has disabled the notifications.
   */
  notification_disabled?: boolean;
  /**
   * if the participant has muted the meeting.
   */
  mute_notification?: boolean;
  /**
   * Count of unread notifications of the participants.
   */
  unread_notification_count?: number;
  /**
   * if the participant is removed from the meeting by the host.
   */
  is_removed?: boolean;
  /**
   * If the participant deleted the meeting.
   */
  deleted_meeting?: boolean;
  /**
   * Latest status updated by the participant
   */
  status_updated_at?: string;
  /**
   * Whether participant attended the meeting or not
   */
  participant_attendance?: number;
}
