/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ReferralMeetingInfoResponseData {
  /**
   * recur_meeting_id of the meeting
   */
  recur_meeting_id?: number;
  /**
   * meeting_id of the meeting
   */
  meeting_id?: number;
  /**
   * subject of the meeting
   */
  subject?: string;
  /**
   * start time of the meeting
   */
  start_time?: string;
  /**
   * end time of the meeting
   */
  end_time?: string;
  /**
   * Location of the meeting
   */
  location?: string;
  /**
   * Longitude of the meeting
   */
  longitude?: string;
  /**
   * Latitude of the meeting
   */
  latitude?: string;
  /**
   * if the meeting is already cancelled or not.
   */
  is_cancelled?: boolean;
  created_at?: string;
  set_recurrence?: number;
  host_contact_number?: string;
  event_category?: number;
  participant_count?: number;
}
