/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RemoveParticipants {
  /**
   * 1 - To add the participants to the whole series,0 - To add to a specific meeting
   */
  set_recurrence: number;
  /**
   * The recur_meeting_id of the meeting in which the participants to be added.
   */
  recur_meeting_id: number;
  /**
   * The meeting_id of the meeting in which the participants to be added.
   */
  meeting_id: number;
  /**
   * The array list of contact numbers of the participants.
   */
  participants?: Array<string>;
}
