/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface StoreFirebaseLink {
  /**
   * The recur_meeting_id for which the link to be created.
   */
  recur_meeting_id: number;
  /**
   * The firebase_link.
   */
  firebase_link: string;
  /**
   * The firebase_link.
   */
  registration_link: string;
}
