/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MeetingInfoResponseData } from './meetingInfoResponseData';
import { UndeliveredMeetingResponseNotificationCount } from './undeliveredMeetingResponseNotificationCount';

export interface UndeliveredMeetingResponse {
  is_error?: boolean;
  status_code?: number;
  display_msg?: string;
  sync_timestamp?: string;
  sampling_rate?: number;
  notification_count?: Array<UndeliveredMeetingResponseNotificationCount>;
  meeting_id_count?: number;
  /**
   * array of meeting info along with participants.
   */
  res_data?: Array<MeetingInfoResponseData>;
}
