/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateParticipantStatus {
  /**
   * 1 - To update the status in the whole series,0 - in a specific meeting
   */
  set_recurrence: number;
  /**
   * The recur_meeting_id of the meeting.
   */
  recur_meeting_id: number;
  /**
   * The meeting_id of the meeting.
   */
  meeting_id: number;
  /**
   * The status of the participant(accepted/declined/tentatively accepted).
   */
  status: number;
}
