/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateLogin {
  /**
   * The login_method type that the user is already registered. 0 - default.
   */
  login_method?: number;
  /**
   * The login_id of the user
   */
  login_id?: string;
  /**
   * The email_id of the user
   */
  email_id?: string;
  app_version?: string;
  /**
   * The OS of the device.
   */
  device_os?: number;
  /**
   * The os_version of the mobile
   */
  device_os_version?: string;
  /**
   * Device make company.
   */
  device_make?: string;
  /**
   * Device model
   */
  device_model?: string;
  /**
   * The device id of the mobile.
   */
  device_id?: string;
}
