/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateLinkStatus {
  /**
   * The recur_meeting_id for which the link has to be activated or deactivated.
   */
  recur_meeting_id: number;
  /**
   * true to active. false to deactivate.
   */
  activate: boolean;
}
