/**
 * Catchup APIs
 * The Catchup API document is intended strictly for internal use only.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ValidateParticipantStatusResponse {
  /**
   * contact_number of the participant
   */
  contact_number: string;
  /**
   * if the participant is already added to the meeting.
   */
  meeting_exists: boolean;
  /**
   * if the participant is registered with Catchup
   */
  registered: boolean;
}
